import os
import random, base64, datetime
os.system("pip install colorama")
from colorama import Fore

os.system("cls")
dictionary = {}
skinname_dictionary = {}

success = 0
failed = 0
directory = os.path.dirname(os.path.abspath(__file__))
count = 1001 # skin name
skin_names = ["YeetDisDude", "yeetdisdude", "ig: y_etd.sdude", "YeetDisDude#0001", "Subscribe", "cXwbBTz8"]
file = os.path.join(directory, "dict.txt") # path for dict.txt
logfile = os.path.join(directory, "logfile.txt") # path for logfile.txt
formats = ["data:image/png;base64,", "data:image/jpeg;base64,", "data:image/gif;base64,", "data:image/bmp;base64,", "data:image/webp;base64,"]

while True:
    current_date = datetime.datetime.now().date()
    current_time = datetime.datetime.now().time()
    b64 = input(f"{Fore.LIGHTCYAN_EX}Enter Base64:{Fore.RESET} ")
    if not b64:
        failed += 1
        print(f"{Fore.RED}[{Fore.RESET}!{Fore.RED}]{Fore.RESET} - {Fore.LIGHTRED_EX}The input is blank. Please enter a valid base64 string.\n{Fore.RESET}")
        continue
    for format in formats:
        if format in b64:
            print(f"{Fore.LIGHTRED_EX}[{Fore.RESET}!{Fore.LIGHTRED_EX}]{Fore.RESET} - prefix found in string, removing...")
            comma_index = b64.index(",")
            b64 = b64[comma_index+1:]
            break
    else:
        1
    try:
        decoded_data = base64.b64decode(b64)
        key = str(count)
        dictionary[key] = b64

        key2 = str(count)
        skinname_dictionary[key2] = random.choice(skin_names)
        count += 1

        success += 1
        print(f"{Fore.LIGHTGREEN_EX}[{Fore.RESET}!{Fore.LIGHTGREEN_EX}]{Fore.RESET} - Saved to dict.txt | Success: {Fore.LIGHTGREEN_EX}{success}{Fore.RESET} | Failed: {Fore.LIGHTRED_EX}{failed}{Fore.RESET}\n")
        with open(logfile, "a") as f:
            f.write(f"\n{current_date} | {current_time} | {b64}")
        with open(file, "w") as f:
            content = f'''Plist for skins Base64

User Skins:
    <key>User Skins</key>
    <string>{str(dictionary)}</string>

Plist for Skin Names:
    <key>User Name Skins</key>
    <string>{str(skinname_dictionary)}</string>

Current Equiped Skin:
    <key>Name Current Skin</key>
    <string>1001</string>

Usage: Replace the lines in the plist with the lines generated by this script\nhttps://github.com/YeetDisDude/pixel-gun-3d/tree/main/skin%20plist%20gen\nMade by: YeetDisDude
'''
            content = content.replace("'", '"')
            f.write(content)
    except:
        failed += 1
        print(f"{Fore.RED}[{Fore.RESET}!{Fore.RED}]{Fore.RESET} - {Fore.LIGHTRED_EX}That string is not a valid base64 encoding.\n{Fore.RESET}")
